"""The accounting kernel: deterministic accounting master data and rules.

Phase 1 covers the chart of accounts, accounting periods, and dimensions. Phase 2
adds journal entries: recording, validation, posting, voiding, and reversal. Phase 3
adds the ledger they post to and the reports derived from it: trial balance,
general ledger, income statement, and balance sheet.

The kernel is usable directly from Python and depends on nothing above it. Every
name a caller needs is re-exported here, so importing this package is also what
registers the persistence models on ``Base.metadata`` and the session hooks that
protect recorded journal entries.
"""

from opensumma.kernel.accounts import (
    activate_account,
    assert_postable,
    chart_of_accounts,
    create_account,
    deactivate_account,
    descendants,
    find_account,
    get_account,
    has_postings,
    postable_accounts,
)
from opensumma.kernel.dimensions import (
    add_dimension_value,
    create_dimension,
    dimensions,
    find_dimension,
    get_dimension,
    get_dimension_value,
    resolve_dimension_value,
)
from opensumma.kernel.enums import (
    LEDGER_STATUSES,
    AccountType,
    IssueCode,
    JournalEntryStatus,
    NormalBalance,
    PeriodStatus,
)
from opensumma.kernel.errors import (
    AccountHasPostingsError,
    AccountTypeMismatchError,
    AlreadyPostedError,
    ClosedPeriodError,
    DuplicateCodeError,
    EntryStatusError,
    ImmutableEntryError,
    InactiveAccountError,
    InactiveDimensionValueError,
    InvalidPeriodRangeError,
    JournalEntryError,
    KernelError,
    NotPostableError,
    OverlappingPeriodError,
    UnknownAccountError,
    UnknownDimensionError,
    UnknownDimensionValueError,
    UnknownJournalEntryError,
    UnknownPeriodError,
    ValidationIssue,
)
from opensumma.kernel.journal import (
    LineInput,
    create_journal_entry,
    get_journal_entry,
    post_journal_entry,
    reverse_journal_entry,
    validate_journal_entry,
    void_journal_entry,
)
from opensumma.kernel.ledger import (
    AccountBalance,
    Activity,
    LedgerLine,
    account_balance,
    activity_before,
    ledger_lines,
    posted_activity,
)
from opensumma.kernel.models import (
    Account,
    AccountingPeriod,
    Dimension,
    DimensionValue,
    JournalEntry,
    JournalLine,
    JournalLineDimension,
)
from opensumma.kernel.periods import (
    assert_period_open,
    close_period,
    create_calendar_year_periods,
    create_period,
    find_period,
    get_period,
    period_for_date,
    periods,
    reopen_period,
)
from opensumma.kernel.reports import (
    BalanceSheet,
    GeneralLedger,
    GeneralLedgerAccount,
    GeneralLedgerLine,
    IncomeStatement,
    StatementLine,
    StatementSection,
    TrialBalance,
    TrialBalanceLine,
    balance_sheet,
    general_ledger,
    income_statement,
    trial_balance,
)
from opensumma.kernel.seed import (
    DEFAULT_CHART_OF_ACCOUNTS,
    DEFAULT_DIMENSIONS,
    AccountSpec,
    DimensionSpec,
    seed_chart_of_accounts,
    seed_dimensions,
)

__all__ = [
    "DEFAULT_CHART_OF_ACCOUNTS",
    "DEFAULT_DIMENSIONS",
    "LEDGER_STATUSES",
    "Account",
    "AccountBalance",
    "AccountHasPostingsError",
    "AccountSpec",
    "AccountType",
    "AccountTypeMismatchError",
    "AccountingPeriod",
    "Activity",
    "AlreadyPostedError",
    "BalanceSheet",
    "ClosedPeriodError",
    "Dimension",
    "DimensionSpec",
    "DimensionValue",
    "DuplicateCodeError",
    "EntryStatusError",
    "GeneralLedger",
    "GeneralLedgerAccount",
    "GeneralLedgerLine",
    "ImmutableEntryError",
    "InactiveAccountError",
    "InactiveDimensionValueError",
    "IncomeStatement",
    "InvalidPeriodRangeError",
    "IssueCode",
    "JournalEntry",
    "JournalEntryError",
    "JournalEntryStatus",
    "JournalLine",
    "JournalLineDimension",
    "KernelError",
    "LedgerLine",
    "LineInput",
    "NormalBalance",
    "NotPostableError",
    "OverlappingPeriodError",
    "PeriodStatus",
    "StatementLine",
    "StatementSection",
    "TrialBalance",
    "TrialBalanceLine",
    "UnknownAccountError",
    "UnknownDimensionError",
    "UnknownDimensionValueError",
    "UnknownJournalEntryError",
    "UnknownPeriodError",
    "ValidationIssue",
    "account_balance",
    "activate_account",
    "activity_before",
    "add_dimension_value",
    "assert_period_open",
    "assert_postable",
    "balance_sheet",
    "chart_of_accounts",
    "close_period",
    "create_account",
    "create_calendar_year_periods",
    "create_dimension",
    "create_journal_entry",
    "create_period",
    "deactivate_account",
    "descendants",
    "dimensions",
    "find_account",
    "find_dimension",
    "find_period",
    "general_ledger",
    "get_account",
    "get_dimension",
    "get_dimension_value",
    "get_journal_entry",
    "get_period",
    "has_postings",
    "income_statement",
    "ledger_lines",
    "period_for_date",
    "periods",
    "post_journal_entry",
    "postable_accounts",
    "posted_activity",
    "reopen_period",
    "resolve_dimension_value",
    "reverse_journal_entry",
    "seed_chart_of_accounts",
    "seed_dimensions",
    "trial_balance",
    "validate_journal_entry",
    "void_journal_entry",
]
