"""Phase 9 acceptance: the deterministic dataset generator.

``erp dataset generate --company acme --transactions 1000 --seed 42`` is run as
the installed command, and a 10,000-transaction company is generated beside it. The
same seed gives the same books and ground truth; the books balance at every month
end; every type of error is injected, and its ground truth matches the books, is
exactly how they differ from the clean books of the same seed, and is enough to
correct them through the workflow. The REST interface serves the books as they are.
"""

import json
import shutil
import subprocess
import sys
from collections.abc import Iterator
from contextlib import contextmanager
from datetime import date
from decimal import Decimal
from pathlib import Path
from typing import Any

import pytest
from fastapi.testclient import TestClient
from sqlalchemy import func, select
from sqlalchemy.orm import Session

from opensumma.api import create_app
from opensumma.datasets import ERROR_TYPES, books_fingerprint, write_dataset
from opensumma.datasets.business import month_end
from opensumma.db import create_engine
from opensumma.kernel import (
    JournalEntry,
    LineInput,
    balance_sheet,
    posted_activity,
    trial_balance,
)
from opensumma.money import ZERO
from opensumma.workflow import (
    ActorType,
    create_actor,
    issue_api_key,
    propose_journal_entry,
    validate_journal_entry,
)

Generated = tuple[Path, dict[str, Any], dict[str, Any]]


def _load(directory: Path) -> Generated:
    return (
        directory,
        json.loads((directory / "manifest.json").read_text()),
        json.loads((directory / "ground_truth.json").read_text()),
    )


@contextmanager
def _session(directory: Path) -> Iterator[Session]:
    engine = create_engine(f"sqlite:///{directory / 'books.db'}")
    try:
        with Session(engine) as session:
            yield session
    finally:
        engine.dispose()


def _net(session: Session, through: date) -> dict[str, Decimal]:
    return {
        account: activity.debits - activity.credits
        for account, activity in posted_activity(session, end=through).items()
        if activity.debits != activity.credits
    }


@pytest.fixture(scope="module")
def acme(tmp_path_factory: pytest.TempPathFactory) -> Generated:
    """1,000 transactions, generated by the installed ``erp`` command."""
    directory = tmp_path_factory.mktemp("acme") / "acme"
    erp = Path(sys.executable).with_name("erp")
    assert erp.is_file(), "the erp command is not installed beside this Python"
    finished = subprocess.run(
        [
            str(erp),
            "dataset",
            "generate",
            "--company",
            "acme",
            "--transactions",
            "1000",
            "--seed",
            "42",
            "--output",
            str(directory),
        ],
        capture_output=True,
        text=True,
        timeout=300,
        check=False,
    )
    assert finished.returncode == 0, finished.stderr
    assert "Generated acme: 1,000 transactions" in finished.stdout
    return _load(directory)


@pytest.fixture(scope="module")
def large(tmp_path_factory: pytest.TempPathFactory) -> Generated:
    directory = tmp_path_factory.mktemp("large") / "globex"
    write_dataset(directory, company="globex", transactions=10_000, seed=42)
    return _load(directory)


def test_deterministic_dataset_generation_works(acme: Generated) -> None:
    directory, manifest, ground_truth = acme
    assert sorted(p.name for p in directory.iterdir()) == [
        "books.db",
        "ground_truth.json",
        "manifest.json",
    ]
    assert manifest["company"] == "acme"
    assert (manifest["seed"], manifest["transactions"]) == (42, 1000)
    with _session(directory) as session:
        assert books_fingerprint(session) == manifest["fingerprint"]
    assert ground_truth["fingerprint"] == manifest["fingerprint"]


def test_seed_produces_reproducible_data(acme: Generated, tmp_path: Path) -> None:
    directory, manifest, _ = acme
    again = write_dataset(
        tmp_path / "again", company="acme", transactions=1000, seed=42
    )
    other = write_dataset(
        tmp_path / "other", company="acme", transactions=1000, seed=43
    )
    assert again.manifest == manifest
    for name in ("manifest.json", "ground_truth.json"):
        assert (tmp_path / "again" / name).read_bytes() == (
            directory / name
        ).read_bytes()
    assert other.manifest["fingerprint"] != manifest["fingerprint"]


def test_a_1000_transaction_dataset_works(acme: Generated, tmp_path: Path) -> None:
    directory, manifest, _ = acme
    with _session(directory) as session:
        entries = session.scalar(select(func.count()).select_from(JournalEntry))
    assert entries == manifest["counts"]["journal_entries"]
    assert manifest["counts"]["customers"] >= 5 and manifest["counts"]["vendors"] == 11

    # The REST interface serves a copy of the books as they are.
    shutil.copyfile(directory / "books.db", tmp_path / "books.db")
    url = f"sqlite:///{tmp_path / 'books.db'}"
    with _session(tmp_path) as session:
        reader = create_actor(
            session, code="reader", name="Reader", actor_type=ActorType.AGENT,
            permissions=["READ_ONLY"],
        )  # fmt: skip
        key = issue_api_key(session, reader)
        session.commit()
    with TestClient(create_app(url)) as api:
        assert api.get("/health").json() == {"status": "ok"}
        trial = api.get(
            "/reports/trial-balance",
            params={"as_of": "2026-12-31"},
            headers={"Authorization": f"Bearer {key}"},
        ).json()
    assert trial["total_debits"] == manifest["year_end"]["trial_balance_total"]


def test_a_10000_transaction_dataset_works(large: Generated) -> None:
    directory, manifest, ground_truth = large
    counts = manifest["counts"]
    added = sum(len(e["actual"]) for e in ground_truth["errors"] if not e["expected"])
    omitted = sum(len(e["expected"]) for e in ground_truth["errors"] if not e["actual"])
    assert counts["journal_entries"] == 10_000 + added - omitted
    assert len(ground_truth["errors"]) == 100
    assert counts["customers"] > 50 and counts["bank_transactions"] > 4000
    with _session(directory) as session:
        assert books_fingerprint(session) == manifest["fingerprint"]


@pytest.mark.parametrize("dataset", ["acme", "large"])
def test_generated_companies_balance(
    dataset: str, request: pytest.FixtureRequest
) -> None:
    directory, manifest, _ = request.getfixturevalue(dataset)
    with _session(directory) as session:
        for month in range(1, 13):
            end = month_end(2026, month)
            trial = trial_balance(session, as_of=end)
            sheet = balance_sheet(session, as_of=end)
            assert trial.is_balanced and sheet.is_balanced, end
            assert sheet.assets.total == sheet.total_liabilities_and_equity
    year_end = manifest["year_end"]
    assert Decimal(year_end["total_assets"]) == Decimal(
        year_end["total_liabilities"]
    ) + Decimal(year_end["total_equity"])


def test_error_injection_works(acme: Generated) -> None:
    directory, _, ground_truth = acme
    errors = ground_truth["errors"]
    assert sorted(e["type"] for e in errors) == sorted(ERROR_TYPES)
    with _session(directory) as session:
        for error in errors:
            for recorded in error["actual"]:
                entry = session.get(JournalEntry, recorded["id"])
                assert entry is not None, error["id"]
                assert entry.entry_date.isoformat() == recorded["entry_date"]
                assert [
                    (line.account.code, str(line.debit), str(line.credit))
                    for line in entry.lines
                ] == [
                    (line["account"], line["debit"], line["credit"])
                    for line in recorded["lines"]
                ], error["id"]


def test_ground_truth_is_preserved(acme: Generated, tmp_path: Path) -> None:
    directory, _, ground_truth = acme
    write_dataset(tmp_path, company="acme", transactions=1000, seed=42, errors=0)
    errors = ground_truth["errors"]
    with _session(directory) as wrong, _session(tmp_path) as right:
        for month in range(1, 13):
            end = month_end(2026, month)
            wrong_net, right_net = _net(wrong, end), _net(right, end)
            difference = {
                account: net
                for account in sorted({*wrong_net, *right_net})
                if (net := wrong_net.get(account, ZERO) - right_net.get(account, ZERO))
            }
            explained: dict[str, Decimal] = {}
            for error in errors:
                for sign, side in ((1, error["actual"]), (-1, error["expected"])):
                    for entry in side:
                        if date.fromisoformat(entry["entry_date"]) > end:
                            continue
                        for line in entry["lines"]:
                            net = Decimal(line["debit"]) - Decimal(line["credit"])
                            explained[line["account"]] = (
                                explained.get(line["account"], ZERO) + sign * net
                            )
            assert difference == {a: n for a, n in sorted(explained.items()) if n}, end


def test_the_ground_truth_is_enough_to_correct_the_books(
    acme: Generated, tmp_path: Path
) -> None:
    directory, _, ground_truth = acme
    (error,) = [e for e in ground_truth["errors"] if e["type"] == "wrong_gl_account"]
    details = error["details"]
    amount = Decimal(error["actual"][0]["lines"][0]["debit"])
    dimensions = error["actual"][0]["lines"][0]["dimensions"]

    shutil.copyfile(directory / "books.db", tmp_path / "books.db")
    with _session(tmp_path) as session:
        agent = create_actor(
            session, code="agent", name="Agent", actor_type=ActorType.AGENT,
            permissions=["READ_ONLY", "PROPOSER"],
        )  # fmt: skip
        correction = propose_journal_entry(
            session,
            actor=agent,
            entry_date=date(2026, 12, 31),
            description=f"Reclassify journal entry {details['journal_entry_id']}",
            lines=[
                LineInput(
                    details["correct_account"], debit=amount, dimensions=dimensions
                ),
                LineInput(
                    details["posted_account"], credit=amount, dimensions=dimensions
                ),
            ],
            reason="The expense was posted to the wrong account.",
            evidence=[f"journal_entry_id={details['journal_entry_id']}"],
        )
        assert validate_journal_entry(session, correction, actor=agent) == []
