"""Database foundation: declarative base, engine creation, and schema migrations.

All persistence goes through SQLAlchemy so the same code runs on SQLite (the
default) and PostgreSQL. Alembic migrations are the single source of truth for
the schema; they ship inside the package so an installed OpenSumma can create
its own databases.
"""

import os

from alembic import command
from alembic.config import Config
from sqlalchemy import Engine, MetaData, event
from sqlalchemy import create_engine as sa_create_engine
from sqlalchemy.engine.interfaces import DBAPIConnection
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.pool import ConnectionPoolEntry

DATABASE_URL_ENV = "OPENSUMMA_DATABASE_URL"
DEFAULT_DATABASE_URL = "sqlite:///opensumma.db"

# Deterministic constraint names keep autogenerated migrations reproducible and
# let SQLite batch migrations locate constraints to alter or drop.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base for all persistence models."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


def get_database_url() -> str:
    """Return the configured database URL, falling back to a local SQLite file."""
    return os.environ.get(DATABASE_URL_ENV, DEFAULT_DATABASE_URL)


def create_engine(url: str | None = None) -> Engine:
    """Create an engine for the application.

    SQLite does not enforce foreign keys unless asked to on every connection;
    referential integrity is not optional for a ledger, so it is always enabled.
    """
    engine = sa_create_engine(url or get_database_url())
    if engine.dialect.name == "sqlite":
        event.listen(engine, "connect", _enable_sqlite_foreign_keys)
    return engine


def _enable_sqlite_foreign_keys(
    dbapi_connection: DBAPIConnection, connection_record: ConnectionPoolEntry
) -> None:
    cursor = dbapi_connection.cursor()
    cursor.execute("PRAGMA foreign_keys=ON")
    cursor.close()


def alembic_config(url: str | None = None) -> Config:
    """Build an Alembic configuration that does not depend on ``alembic.ini``."""
    # Alembic options use ConfigParser interpolation, so a literal "%" (common
    # in URL-encoded passwords) must be escaped.
    escaped_url = (url or get_database_url()).replace("%", "%%")
    config = Config()
    config.set_main_option("script_location", "opensumma:migrations")
    config.set_main_option("sqlalchemy.url", escaped_url)
    return config


def init_db(url: str | None = None) -> None:
    """Create the database schema, or upgrade it to the latest migration."""
    command.upgrade(alembic_config(url), "head")
