import io
import sqlite3
from collections.abc import Iterator
from contextlib import closing, contextmanager
from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from alembic.runtime.migration import MigrationContext
from alembic.script import ScriptDirectory
from sqlalchemy import Engine

REPO_ROOT = Path(__file__).resolve().parents[2]


@pytest.fixture
def cli_config(database_url: str) -> Config:
    """The ``alembic`` command-line configuration, pointed at the test database."""
    config = Config(REPO_ROOT / "alembic.ini")
    config.set_main_option("sqlalchemy.url", database_url)
    return config


def current_revision(engine: Engine) -> str | None:
    with engine.connect() as connection:
        return MigrationContext.configure(connection).get_current_revision()


def test_migration_history_has_a_single_head(cli_config: Config) -> None:
    assert len(ScriptDirectory.from_config(cli_config).get_heads()) == 1


def test_upgrade_and_downgrade_round_trip(cli_config: Config, engine: Engine) -> None:
    head = ScriptDirectory.from_config(cli_config).get_current_head()

    command.upgrade(cli_config, "head")
    assert current_revision(engine) == head

    command.downgrade(cli_config, "base")
    assert current_revision(engine) is None

    command.upgrade(cli_config, "head")
    assert current_revision(engine) == head


def test_models_match_migrations(cli_config: Config) -> None:
    """Every persistence model change must ship with a migration."""
    command.upgrade(cli_config, "head")
    command.check(cli_config)  # raises AutogenerateDiffsDetected on drift


def test_postgresql_sql_can_be_generated_offline() -> None:
    """``alembic upgrade head --sql`` works for PostgreSQL, where DBAs would use it.

    It also pins the order Phase 2 depends on: PostgreSQL refuses a foreign key
    whose target columns are not already unique.
    """
    output = io.StringIO()
    config = Config(REPO_ROOT / "alembic.ini", output_buffer=output)
    config.set_main_option("sqlalchemy.url", "postgresql://opensumma@localhost/offline")

    command.upgrade(config, "head", sql=True)
    sql = output.getvalue()

    assert "CREATE TABLE journal_line_dimension" in sql
    assert sql.index("ADD CONSTRAINT uq_dimension_value_id") < sql.index(
        "CREATE TABLE journal_line_dimension"
    )
    assert "CREATE INDEX ix_journal_entry_entry_date" in sql
    assert "CREATE TABLE accounting_object" in sql
    assert "data JSON NOT NULL" in sql
    assert "CREATE TABLE workflow_transition" in sql
    assert "UPDATE accounting_object SET counterparty_id" in sql
    assert "CREATE TABLE audit_event" in sql
    assert "CREATE INDEX ix_audit_event_subject" in sql
    assert "CREATE TABLE api_key" in sql
    assert sql.index("CREATE TABLE journal_entry") < sql.index(
        "CREATE TABLE accounting_object_entry"
    )


PHASE_4 = "de5016324ad2"
PHASE_5 = "71801d14980d"


@contextmanager
def _sqlite(database_url: str) -> Iterator[sqlite3.Connection]:
    """A raw connection to the test database, committed and always closed.

    ``sqlite3.Connection`` as a context manager commits but does not close, which
    Python 3.13 reports as an unclosed-database ResourceWarning.
    """
    path = database_url.removeprefix("sqlite:///")
    with closing(sqlite3.connect(path)) as db, db:
        yield db


def _check_constraints(database_url: str, table: str) -> set[str]:
    with _sqlite(database_url) as connection:
        (sql,) = connection.execute(
            "SELECT sql FROM sqlite_master WHERE type = 'table' AND name = ?", (table,)
        ).fetchone()
    return {
        part.split(" CHECK")[0].strip()
        for part in sql.split("CONSTRAINT")
        if " CHECK" in part
    }


def test_rebuilding_a_table_keeps_its_check_constraints(
    cli_config: Config, database_url: str
) -> None:
    """Batch migrations rebuild SQLite tables; ``alembic check`` cannot see a lost
    CHECK, so this looks at the rebuilt table directly."""
    command.upgrade(cli_config, "head")
    assert _check_constraints(database_url, "accounting_object") == {
        "ck_accounting_object_object_type_is_valid",
        "ck_accounting_object_source_not_empty",
        "ck_accounting_object_status_is_valid",
    }


def test_entity_ids_become_counterparties_and_come_back(
    cli_config: Config, database_url: str
) -> None:
    command.upgrade(cli_config, PHASE_4)
    rows = [
        ("vendor_bill", "V-OLD"),
        ("vendor_payment", "V-OLD"),
        ("customer_invoice", "C-OLD"),
        ("sales_order", "C-OLD"),
        ("bank_transaction", "BANKCO"),
        ("expense", None),
    ]
    stamp = "2026-03-01 09:00:00.000000"
    with _sqlite(database_url) as connection:
        connection.executemany(
            "INSERT INTO accounting_object (object_type, status, occurred_at, source,"
            " entity_id, data, created_at, updated_at)"
            " VALUES (?, 'OBSERVED', ?, 'seed', ?, '{}', ?, ?)",
            [(kind, stamp, entity, stamp, stamp) for kind, entity in rows],
        )

    command.upgrade(cli_config, PHASE_5)
    with _sqlite(database_url) as connection:
        created = connection.execute(
            "SELECT code, name, kind FROM counterparty ORDER BY code"
        ).fetchall()
        named = connection.execute(
            "SELECT o.object_type, c.code FROM accounting_object o"
            " LEFT JOIN counterparty c ON c.id = o.counterparty_id ORDER BY o.id"
        ).fetchall()
    assert created == [
        ("BANKCO", "BANKCO", "VENDOR"),  # named by no customer-type object
        ("C-OLD", "C-OLD", "CUSTOMER"),
        ("V-OLD", "V-OLD", "VENDOR"),
    ]
    assert named == [
        ("vendor_bill", "V-OLD"),
        ("vendor_payment", "V-OLD"),
        ("customer_invoice", "C-OLD"),
        ("sales_order", "C-OLD"),
        ("bank_transaction", "BANKCO"),
        ("expense", None),
    ]

    command.downgrade(cli_config, PHASE_4)
    with _sqlite(database_url) as connection:
        restored = connection.execute(
            "SELECT object_type, entity_id FROM accounting_object ORDER BY id"
        ).fetchall()
    assert restored == rows
    assert "ck_accounting_object_entity_id_not_empty" in _check_constraints(
        database_url, "accounting_object"
    )
