from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from alembic.runtime.migration import MigrationContext
from alembic.script import ScriptDirectory
from sqlalchemy import Engine

REPO_ROOT = Path(__file__).resolve().parents[2]


@pytest.fixture
def cli_config(database_url: str) -> Config:
    """The ``alembic`` command-line configuration, pointed at the test database."""
    config = Config(REPO_ROOT / "alembic.ini")
    config.set_main_option("sqlalchemy.url", database_url)
    return config


def current_revision(engine: Engine) -> str | None:
    with engine.connect() as connection:
        return MigrationContext.configure(connection).get_current_revision()


def test_migration_history_has_a_single_head(cli_config: Config) -> None:
    assert len(ScriptDirectory.from_config(cli_config).get_heads()) == 1


def test_upgrade_and_downgrade_round_trip(cli_config: Config, engine: Engine) -> None:
    head = ScriptDirectory.from_config(cli_config).get_current_head()

    command.upgrade(cli_config, "head")
    assert current_revision(engine) == head

    command.downgrade(cli_config, "base")
    assert current_revision(engine) is None

    command.upgrade(cli_config, "head")
    assert current_revision(engine) == head


def test_models_match_migrations(cli_config: Config) -> None:
    """Every persistence model change must ship with a migration."""
    command.upgrade(cli_config, "head")
    command.check(cli_config)  # raises AutogenerateDiffsDetected on drift
