import io
from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from alembic.runtime.migration import MigrationContext
from alembic.script import ScriptDirectory
from sqlalchemy import Engine, inspect, text

REPO_ROOT = Path(__file__).resolve().parents[2]


@pytest.fixture
def cli_config(database_url: str) -> Config:
    """The ``alembic`` command-line configuration, pointed at the test database."""
    config = Config(REPO_ROOT / "alembic.ini")
    # Options are interpolated, so a "%" in the URL, as in an encoded password,
    # is written "%%", as opensumma.db.alembic_config writes it.
    config.set_main_option("sqlalchemy.url", database_url.replace("%", "%%"))
    return config


def current_revision(engine: Engine) -> str | None:
    with engine.connect() as connection:
        return MigrationContext.configure(connection).get_current_revision()


def test_migration_history_has_a_single_head(cli_config: Config) -> None:
    assert len(ScriptDirectory.from_config(cli_config).get_heads()) == 1


def test_upgrade_and_downgrade_round_trip(cli_config: Config, engine: Engine) -> None:
    head = ScriptDirectory.from_config(cli_config).get_current_head()

    command.upgrade(cli_config, "head")
    assert current_revision(engine) == head

    command.downgrade(cli_config, "base")
    assert current_revision(engine) is None

    command.upgrade(cli_config, "head")
    assert current_revision(engine) == head


def test_models_match_migrations(cli_config: Config) -> None:
    """Every persistence model change must ship with a migration."""
    command.upgrade(cli_config, "head")
    command.check(cli_config)  # raises AutogenerateDiffsDetected on drift


def test_postgresql_sql_can_be_generated_offline() -> None:
    """``alembic upgrade head --sql`` works for PostgreSQL, where DBAs would use it.

    It also pins the order Phase 2 depends on: PostgreSQL refuses a foreign key
    whose target columns are not already unique.
    """
    output = io.StringIO()
    config = Config(REPO_ROOT / "alembic.ini", output_buffer=output)
    config.set_main_option("sqlalchemy.url", "postgresql://opensumma@localhost/offline")

    command.upgrade(config, "head", sql=True)
    sql = output.getvalue()

    assert "CREATE TABLE journal_line_dimension" in sql
    assert sql.index("ADD CONSTRAINT uq_dimension_value_id") < sql.index(
        "CREATE TABLE journal_line_dimension"
    )
    assert "CREATE INDEX ix_journal_entry_entry_date" in sql
    assert "CREATE TABLE accounting_object" in sql
    assert "data JSON NOT NULL" in sql
    assert "CREATE TABLE workflow_transition" in sql
    assert "UPDATE accounting_object SET counterparty_id" in sql
    assert "CREATE TABLE audit_event" in sql
    assert "CREATE INDEX ix_audit_event_subject" in sql
    assert "CREATE TABLE api_key" in sql
    assert "UPDATE journal_line SET amount" in sql
    assert sql.index("CREATE TABLE journal_entry") < sql.index(
        "CREATE TABLE accounting_object_entry"
    )


PHASE_4 = "de5016324ad2"
PHASE_5 = "71801d14980d"
PHASE_7 = "dab3bc95c36e"
SIGNED_AMOUNTS = "db546c4d06cf"


def _check_constraints(engine: Engine, table: str) -> set[str]:
    return {
        str(constraint["name"])
        for constraint in inspect(engine).get_check_constraints(table)
    }


def test_rebuilding_a_table_keeps_its_check_constraints(
    cli_config: Config, engine: Engine
) -> None:
    """Batch migrations rebuild SQLite tables; ``alembic check`` cannot see a lost
    CHECK, so this looks at the rebuilt table directly."""
    command.upgrade(cli_config, "head")
    assert _check_constraints(engine, "accounting_object") == {
        "ck_accounting_object_object_type_is_valid",
        "ck_accounting_object_source_not_empty",
        "ck_accounting_object_status_is_valid",
    }
    assert _check_constraints(engine, "journal_line") == {
        "ck_journal_line_line_number_positive"
    }


def test_entity_ids_become_counterparties_and_come_back(
    cli_config: Config, engine: Engine
) -> None:
    command.upgrade(cli_config, PHASE_4)
    rows = [
        ("vendor_bill", "V-OLD"),
        ("vendor_payment", "V-OLD"),
        ("customer_invoice", "C-OLD"),
        ("sales_order", "C-OLD"),
        ("bank_transaction", "BANKCO"),
        ("expense", None),
    ]
    with engine.begin() as connection:
        connection.execute(
            text(
                "INSERT INTO accounting_object (object_type, status, occurred_at,"
                " source, entity_id, data, created_at, updated_at) VALUES (:kind,"
                " 'OBSERVED', :stamp, 'seed', :entity, '{}', :stamp, :stamp)"
            ),
            [
                {"kind": kind, "entity": entity, "stamp": "2026-03-01 09:00:00+00:00"}
                for kind, entity in rows
            ],
        )

    command.upgrade(cli_config, PHASE_5)
    with engine.connect() as connection:
        created = connection.execute(
            text("SELECT code, name, kind FROM counterparty ORDER BY code")
        ).all()
        named = connection.execute(
            text(
                "SELECT o.object_type, c.code FROM accounting_object o"
                " LEFT JOIN counterparty c ON c.id = o.counterparty_id ORDER BY o.id"
            )
        ).all()
    assert created == [
        ("BANKCO", "BANKCO", "VENDOR"),  # named by no customer-type object
        ("C-OLD", "C-OLD", "CUSTOMER"),
        ("V-OLD", "V-OLD", "VENDOR"),
    ]
    assert named == [
        ("vendor_bill", "V-OLD"),
        ("vendor_payment", "V-OLD"),
        ("customer_invoice", "C-OLD"),
        ("sales_order", "C-OLD"),
        ("bank_transaction", "BANKCO"),
        ("expense", None),
    ]

    command.downgrade(cli_config, PHASE_4)
    with engine.connect() as connection:
        restored = connection.execute(
            text("SELECT object_type, entity_id FROM accounting_object ORDER BY id")
        ).all()
    assert restored == rows
    assert "ck_accounting_object_entity_id_not_empty" in _check_constraints(
        engine, "accounting_object"
    )


def _insert_posted_entry(engine: Engine, lines: str) -> None:
    """A posted entry with ``lines``, the VALUES of an INSERT into journal_line,
    on accounts 1 and 2, and a dimension value for line 1."""
    stamp = {"stamp": "2026-03-01 09:00:00+00:00", "yes": True}
    with engine.begin() as connection:
        connection.execute(
            text(
                "INSERT INTO account (id, code, name, account_type, normal_balance,"
                " is_active, created_at, updated_at) VALUES"
                " (1, '6100', 'Hosting', 'EXPENSE', 'DEBIT', :yes, :stamp, :stamp),"
                " (2, '1111', 'Bank', 'ASSET', 'DEBIT', :yes, :stamp, :stamp)"
            ),
            stamp,
        )
        connection.execute(
            text(
                "INSERT INTO dimension (id, code, name, created_at, updated_at)"
                " VALUES (1, 'DEPARTMENT', 'Department', :stamp, :stamp)"
            ),
            stamp,
        )
        connection.execute(
            text(
                "INSERT INTO dimension_value (id, dimension_id, code, name, is_active,"
                " created_at, updated_at)"
                " VALUES (1, 1, 'ENG', 'Engineering', :yes, :stamp, :stamp)"
            ),
            stamp,
        )
        connection.execute(
            text(
                "INSERT INTO journal_entry (id, entry_date, description, status,"
                " posted_at, created_at, updated_at)"
                " VALUES (1, '2026-03-02', 'AWS', 'POSTED', :stamp, :stamp, :stamp)"
            ),
            stamp,
        )
        connection.execute(text(f"INSERT INTO journal_line {lines}"))
        connection.execute(
            text(
                "INSERT INTO journal_line_dimension"
                " (journal_line_id, dimension_id, dimension_value_id)"
                " VALUES (1, 1, 1)"
            )
        )


def test_debits_and_credits_become_signed_amounts_and_come_back(
    cli_config: Config, engine: Engine
) -> None:
    command.upgrade(cli_config, PHASE_7)
    _insert_posted_entry(
        engine,
        "(id, journal_entry_id, line_number, account_id, debit, credit, memo)"
        " VALUES (1, 1, 1, 1, 12050, 0, 'compute'), (2, 1, 2, 2, 0, 12050, NULL)",
    )

    command.upgrade(cli_config, SIGNED_AMOUNTS)
    with engine.connect() as connection:
        upgraded = connection.execute(
            text("SELECT id, amount, memo FROM journal_line ORDER BY id")
        ).all()
        tagged = connection.execute(
            text("SELECT journal_line_id FROM journal_line_dimension")
        ).all()
    assert upgraded == [(1, 12050, "compute"), (2, -12050, None)]
    assert tagged == [(1,)]  # rebuilding the table keeps what refers to its rows
    assert _check_constraints(engine, "journal_line") == {
        "ck_journal_line_line_number_positive"
    }

    command.downgrade(cli_config, PHASE_7)
    with engine.connect() as connection:
        restored = connection.execute(
            text("SELECT id, debit, credit, memo FROM journal_line ORDER BY id")
        ).all()
    assert restored == [(1, 12050, 0, "compute"), (2, 0, 12050, None)]
    assert "ck_journal_line_one_positive_side" in _check_constraints(
        engine, "journal_line"
    )


def test_a_zero_line_keeps_the_books_from_going_back_to_debits_and_credits(
    cli_config: Config, engine: Engine
) -> None:
    command.upgrade(cli_config, SIGNED_AMOUNTS)
    _insert_posted_entry(
        engine,
        "(id, journal_entry_id, line_number, account_id, amount, memo)"
        " VALUES (1, 1, 1, 1, 0, NULL), (2, 1, 2, 2, 0, NULL)",
    )

    with pytest.raises(RuntimeError, match="zero amount"):
        command.downgrade(cli_config, PHASE_7)
    assert current_revision(engine) == SIGNED_AMOUNTS
    with engine.connect() as connection:
        kept = connection.execute(
            text("SELECT id, amount FROM journal_line ORDER BY id")
        ).all()
    assert kept == [(1, 0), (2, 0)]
